### ISSUE TITLE
Error encountered when run  "docker run -p 5001:5001 know-my-doc"

### ISSUE THREAD

**Issue by norsizu** [jainsid24/know-my-doc#2]
Hello,

I have encountered an issue while attempting to use "docker run -p 5001:5001 know-my-doc" after exporting my blog posts into over 800 txt documents. The process started smoothly and proceeded for several hundred lines after "Reading document from string", but then abruptly displayed an error report.

I am using a macOS system and the documents are encoded in Chinese utf-8. Can you please help me understand what went wrong?

The error codes are as follows:

Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1050, in main
    cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/app/app.py", line 7, in <module>
    import chat
  File "/app/chat.py", line 32, in <module>
    for webpage in webpages:
TypeError: 'NoneType' object is not iterable

**Comment by dat4c0ded** [comment]
got the same issue

**Comment by dat4c0ded** [comment]
Using mac apple chip.

**Comment by StephanDeida** [comment]
Can't your project execute in Windows?

**Comment by incert-og** [comment]
got the same issue. could you support mac OS?
